---
- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
- name: Install python-dev
  apt:
    name: python-dev
    state: present
- name: Install libkrb5-dev
  apt:
    name: libkrb5-dev
    state: present
- name: Install krb5-user
  apt:
    name: krb5-user
    state: present