---
- name: backup krb5.conf
  copy:
    src: /etc/krb5.conf
    dest: /etc/krb5.conf.backup
- name: Configure krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
